# -*- coding: utf-8 -*-
"""TTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iJD-KxOnX85BuVj1xcBFpHu-bDI4mN4O
"""

! pip install easyocr
! pip install speechbrain

import easyocr
reader = easyocr.Reader(['en']) # this needs to run only once to load the model into memory
import speechbrain
import io
import numpy as np
from speechbrain.inference import FastSpeech2, HIFIGAN
from IPython.display import Audio, display
import pandas as pd
# Load the models
fastspeech2 = FastSpeech2.from_hparams(source="speechbrain/tts-fastspeech2-ljspeech", savedir="pretrained_models/tts-fastspeech2-ljspeech")
hifi_gan = HIFIGAN.from_hparams(source="speechbrain/tts-hifigan-ljspeech", savedir="pretrained_models/tts-hifigan-ljspeech")

main_df = pd.DataFrame(columns=["Sentence", "Mp3_Path"])

import re
from scipy.io.wavfile import write



# result = reader.readtext('/content/DQbBxMu.jpg')
# text = ''
# for words in result:
#   text += words[1]+ ' '

# text = text[:-1]

text = 'Hey there howre you'

split_text = re.split(r'[.!;,?]', text)

print(split_text)

for sentence in split_text:
  if(len(sentence) > 0):
    print(sentence)
    # Generate mel spectrogram
    mel_output = fastspeech2.encode_text([sentence], pace=1.3, pitch_rate=1.0, energy_rate=1.1)[0]

    # Generate waveform
    waveform = hifi_gan.decode_batch(spectrogram=mel_output, hop_len=1)

    # Convert to numpy array
    audio_data = waveform.squeeze().cpu().numpy()
    audio_data = (audio_data * 32767).astype(np.int16)
    sampling_rate = 22050  # Replace with the actual sampling rate
    file_name = sentence.replace(' ','_')

    write(f'{file_name}.wav', sampling_rate, audio_data)
    new_row = pd.DataFrame({'Sentence': [sentence], 'Mp3_Path': [f'{file_name}.wav']})
    main_df = pd.concat([main_df, new_row], ignore_index=True)

    # Create an audio player
    display(Audio(audio_data, rate=22050))  # 22050 Hz is a common speech sample rate

main_df

main_df