# Generated by Django 5.1.7 on 2025-03-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(unique=True)),
                ('mp3_path', models.FileField(upload_to='generated_audio/')),
            ],
        ),
    ]
